site_name: SPOEF - documentation

repo_url: https://github.com/JanBargeman/SPOEF
site_url: https://janbargeman.github.io/SPOEF/
site_description: Getting started with Signal Processing features for transaction data
site_author: Jan Bargeman

use_directory_urls: false

nav:
  - Home: index.md
  - Getting started:
    - Installation: getting_started/install.md
    - Minimal working example: tutorials/minimal_working_example.md
  - Tutorials:
    - Minimal working example: tutorials/minimal_working_example.md
    - Regular features: tutorials/regular_features.md
    - Transformed features: tutorials/transformed_features.md
    - Features summary: tutorials/features_summary.md


plugins:
  - mkdocstrings:
      handlers:
          python:
            selection:
              inherited_members: true
              filters:
                - "!^Base"
                - "!^_"  # exlude all members starting with _
                - "^__init__$"  # but always include __init__ modules and methods
            rendering:
              show_root_toc_entry: false
      watch:
        - SPOEF
  - search
  - mknotebooks:
      enable_default_jupyter_cell_styling: true
      enable_default_pandas_dataframe_styling: true

copyright: CopyRight &copy; 2021

theme:
  name: mkdocs
  font:
    text: Ubuntu
    code: Ubuntu Mono
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: blue
    accent: yellow


markdown_extensions:
  - codehilite
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      permalink: true
